#ifndef CONSTANTS_H_INCLUDED
#define CONSTANTS_H_INCLUDED

#define ROOT_NODE 0
#define DEFAULT_TAG 0

#define RECEIVE_BUFFER_SIZE 100000

#define INVALID_FITNESS_VALUE INT_MAX

#define LOCAL_POPULATION_SIZE 58
#define LOCAL_OPTIMIZATION_EPOCHES 10000

#define NUMBER_OF_BROADCASTS 67

#define REELS_SIZE 5
#define REEL_SIZE 63
#define ROWS_SIZE 3

#define INVALID_REELS_PENALTY 10000

#endif
